apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 50s
    spec:
      containers:
      - image: hctung57/object-detection-arm:4.6.1.10@sha256:7361b88965a4bb39a693450902ad660e1722f4a9da677b36374318cc0023d771
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - curl "http://0.0.0.0:8080/api/terminate"
        ports:
        - containerPort: 8080
